### ISSUE TITLE
Accessible text for media files

### ISSUE THREAD

**Issue by paulrobertlloyd** [importantimport/fff#7]
This is a really interesting project! It brings to mind [something I’ve noticed with these competing formats in the past](https://paulrobertlloyd.com/articles/2021/01/disagreement/), too.

Looking through your spec, I see that `alt` was previously provided, but removed in #2. Alternative text is important to include when thinking about hosting content online, and most social networks now provide much better support for adding and viewing this information.

Here’s a Microformats representation of a photo with alt text:

```json
"photo": [
  {
    "value": "https://cdn.example/globe.gif",
    "alt": "Spinning globe animation"
  }
]
```

On my own projects, I use the following in my front matter:

```yaml
photo:
  - url: https://cdn.example/globe.gif
    alt: Spinning globe animation
```

HTML also allows authors to provide fallback content for audio and video, so I would expect a means for alternative content to be represented for those values too, i.e.:

```json
"video": [
  {
    "value": "https://cdn.example/globe.mp4",
    "alt": "Spinning globe animation"
  }
]
```

**Comment by kwaa** [comment]
The current [FFF Object Media](https://fff.js.org/version/0.4.html#additional) allows to include any attribute available in HTML.
like this:

```ts
image:
  - src: 'https://cdn.example/globe.gif'
    alt: 'Spinning globe animation'
    source:
      - srcset: 'https://cdn.example/globe444.gif'
        media: '(min-width:444px)'
      - srcset: 'https://cdn.example/globe666.gif'
        media: '(min-width:666px)'
    figcaption: 'Spinning globe animation'
```

However, despite being available in the spec, I really don't have support for it in my project at the moment.
I would consider returning to `alt` values as a simple fallback option.

**Comment by kwaa** [comment]
Oh, I forgot about this issue, sry.

FFF 0.5 adds examples of object media (above) and no longer considers restoring individual `alt` variables. 

https://github.com/importantimport/fff/commit/bc95bcdebefeb3ae9e5dc1e2499ecfc335272e0c
